#!/usr/bin/env bash
#Bash script that configures an Ubuntu server

cp /etc/hosts ~/etc/host.new
echo "127.0.0.1	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/etc/hosts.new /etc/hosts
